services:
  - type: web
    name: sladkiy-kvest-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /healthcheck
    envVars:
      - key: BOT_TOKEN
        sync: false
